# Generated by Django 4.2.6 on 2023-10-24 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_habit', models.CharField(max_length=80, verbose_name='Место выполнения привычки')),
                ('time_habit', models.TimeField(verbose_name='Время привычки')),
                ('get_habit', models.CharField(max_length=200, verbose_name='Что делаем(например, приседаем)')),
                ('nice_habit', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('associated_habit', models.CharField(max_length=100, verbose_name='Приятная связанная привычка ')),
                ('period_habit', models.CharField(choices=[('Каждый день', 'Каждый день'), ('Один раз в неделю', 'Один раз в неделю'), ('Два раза в неделю', 'Два раза в неделю'), ('Три раза в неделю', 'Три раза в неделю'), ('Четыре раза в неделю', 'Четыре раза в неделю'), ('Пять раз в неделю', 'Пять раз в неделю'), ('Шесть раз в неделю', 'Шесть раз в неделю')], verbose_name='Периодичность')),
                ('reward_habit', models.CharField(max_length=50, verbose_name='Награда за выполнение привычки')),
                ('time_limit', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение привычки (в секундах)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичность')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
