# Generated by Django 4.2.6 on 2023-10-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(verbose_name='Публичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='nice_habit',
            field=models.BooleanField(verbose_name='Приятная привычка'),
        ),
    ]
